### PR TITLE
added aria-current = "page"

### PR DESCRIPTION
**Pull request by pratyush1712**
## Trello Task
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;i171O3j0&#x2F;398-the-sidebar-navigation-lacks-wai-aria-markup-to-indicate-which-item-is-the-current-page">The sidebar navigation lacks WAI-ARIA markup to indicate which item is the current page</a></blockquote>

### Summary

- added aria-current="page" to the links on the sidebar to indicate the current page.

### Test Plan
- Could see aria-current = "page" in the HTML elements using inspect

### CODE REVIEW

**Comment by RohitValiveti** [comment]
Hey Prayush. Good work on this task! From my testing, it looks like the aria-current page is only properly shown for the Home page on admin, but not for any of the other pages (See image below). Looking at the Trello task, it seems like the current page indication is also needed for all other pages.
Screen Shot 2022-10-23 at 10 38 54 PM

**Comment by andrewschoi** [comment]
Hey Pratyush, good initiative on this task! Like Rohit mentioned, I think the current page should be consistent on all pages.

**Review by RohitValiveti — DISMISSED** [review]
Hey Pratyush, the changes seem to be working properly from my testing. Should be good to merge!

**Review by RohitValiveti — APPROVED** [review]
LGTM!

**Pull request merged**
