### PR TITLE
Change schedule page heading on student portal

### PR DESCRIPTION
**Pull request by andrewschoi**
- change from "Hi, <first name>" to "Schedule" on schedule page on the student portal

### CODE REVIEW

**Review by harrisonchin2523 — CHANGES_REQUESTED** [review]
I might be nitpicky, but on the Figma the name aligns perfectly with the collapsible and with your changes they're just a little to the right. See below: 
Screenshot 2022-12-06 at 2 22 05 PM

**Comment by RohitValiveti** [comment]
Hey Andrew, good work on the alignment fix. I checked on Safari and Chrome, and the changes look identical to the Figma.

**Review by harrisonchin2523 — APPROVED** [review]
Good work on the fix! The heading aligns perfectly now.

**Comment by pratyush1712** [comment]
Oops, I missed this pr. I saw an incomplete trello task and assigned to Rohit, and I think Rohit finished the task. So, closing this for now

**Pull request closed without merging**
