### PR TITLE
Modal cleanup asc269

### PR DESCRIPTION
**Pull request by andrewschoi**
Edit rider information more accurately represents Figma
-Fixed responsive design issues for small screen width as documented in trello
-Gave error messages more descriptive names

### CODE REVIEW

**Review by harrisonchin2523 — CHANGES_REQUESTED** [review]
If we look at the Figma, there is a last name input box that is needed, but you have condensed the first name and last name boxes into one name box which may not be true to the design. In addition, the error messages are not entirely accurate to the ones listed in the Figma as well as the positioning of the error messages are not quite underneath the box.
Screen Shot 2022-10-19 at 8 06 57 PM
Overall though, the positioning of the boxes and text in the modal looks great!

**Comment by RohitValiveti** [comment]
Nice work Andrew! The modal and errors looks much cleaner now. Some styling differences I noticed: the place holder text for the last name input field says "first name". Also, for consistency wit the Figma, I think the place holder text should be capitalized. Besides that, everything looks good!

**Review by epicdragon44 — APPROVED** [review]
Looks like the necessary issues were addressed! Approving for merge.

**Comment by namanhboi** [comment]
close pr

**Pull request closed without merging**
