### PR TITLE
Add location fix

### PR DESCRIPTION
**Pull request by pratyush1712**
### Summary

This pr fixes the issue of adding a location. Earlier, adding a location used to crash the frontend. Resolved those issues.

### Test Plan
Frontend works

https://user-images.githubusercontent.com/80096811/221570195-36294eba-1244-4bd4-ad3b-223632ddd2f2.mp4

### CODE REVIEW

**Review by harrisonchin2523 — CHANGES_REQUESTED** [review]
Hey Pratyush, I like the changes you made, and they seem to work on your end based off the video you attached and the fact that I can see this new location on my end. However, I seem to be running into issues with CryptoJS. I tried to run npm i to install any missing packagers, but I can't seem to get the server running with these changes. Here's a screenshot of the error below:
Screenshot 2023-02-28 at 5 14 05 PM
Let me know if there's something I'm missing and I'll review it ASAP!

**Comment by Enochen** [comment]
@harrisonchin2523 There was a previous change bundled with the Dockerization diff where `npm run dev` is the command you want to run in the `server` folder if you want to run the server without first building (aka in dev environments). You can also do `npm run build` and `npm start` if you do want to build and run locally.

**Review by harrisonchin2523 — APPROVED** [review]

**Comment by harrisonchin2523** [comment]
@Enochen 
 gotcha, thanks!

**Comment by harrisonchin2523** [comment]
> @harrisonchin2523 There was a previous change bundled with the Dockerization diff where `npm run dev` is the command you want to run in the `server` folder if you want to run the server without first building (aka in dev environments). You can also do `npm run build` and `npm start` if you do want to build and run locally.

gotcha, thanks!

**Pull request merged**
