### PR TITLE
Added my name (andrew choi) to the readme!

### PR DESCRIPTION
**Pull request by andrewschoi**
### Summary 

Added my name to the readme!

### Breaking Changes  

<!-- - Database schema change (anything that changes DynamoDB document structure)
<!-- - Other change that could cause problems (Detailed in notes)

### CODE REVIEW

**Review by harrisonchin2523 — COMMENTED** [review]
looks good andrew! nice job adding to the readme

**Review by fengyuli2002 — DISMISSED** [review]
Welcome to the team!

**Comment by michaeltorku** [comment]
You have to run the formatter - 'npm run format' before all pushes to the codebase. Also sign the CLA so we can get this merged as soon as possible

**Review by michaeltorku — CHANGES_REQUESTED** [review]
There's changes from a different branch, remove them. This PR should only change the readme file

**Comment by michaeltorku** [comment]
Terminated - Cause: erroneous inclusions

**Pull request closed without merging**
