### PR TITLE
Locations modal

### PR DESCRIPTION
**Pull request by jj534**
### Summary 

1. add new location with the location modal
2. edit existing location with the location modal

### Test Plan 
image
image
image

### CODE REVIEW

**Review by mg2239 — CHANGES_REQUESTED** [review]
havent had a chance to actually run this yet but here are a few things i noticed scanning through the code

**Comment by jj534** [comment]
@mg2239 I applied the changes you requested! feel free to let me know if there's anything else that I should fix

**Review by mg2239 — APPROVED** [review]
really nice work!

**Comment by jj534** [comment]
@mg2239  I'll resolve the merge conflicts and merge within 36 hours. sorry about the delay :((

**Pull request merged**
