### PR TITLE
Update Rider Web schedule on edit or cancel

### PR DESCRIPTION
**Pull request by mg2239**
### Summary 

When editing and cancelling rides, the schedule on Rider Web now updates automatically.

### Test Plan 

Run the frontend, schedule a ride, and edit/cancel it.

### CODE REVIEW

**Review by harrisonchin2523 — COMMENTED** [review]
When I edit a scheduled ridetime to a different one, the ride that was previously in the scheduled rides part of the website moves to the unscheduled rides part. I'm not sure if that's correct based off of the names. The live editing is working as intended though which is good!

**Comment by mg2239** [comment]
> When I edit a scheduled ridetime to a different one, the ride that was previously in the scheduled rides part of the website moves to the unscheduled rides part. I'm not sure if that's correct based off of the names. The live editing is working as intended though which is good!

that's intended, since if we change a ride, the changes might conflict with the previously assigned driver's schedule

**Comment by michaeltorku** [comment]
I got this error while trying to look at the riders page (while logged in as an admin). Might it be because of the previous accessibility PR?
image

**Review by michaeltorku — CHANGES_REQUESTED** [review]
rider web doesn't allow me to request a ride (it doesn't allow me to select a location)

**Comment by mg2239** [comment]
@michaeltorku just merged master, try repulling and testing again

**Review by harrisonchin2523 — APPROVED** [review]
Editing/adding a ride does update automatically

**Pull request closed without merging**
