### PR TITLE
Refactor RidesTable to use new table components

### PR DESCRIPTION
**Pull request by pihucode**
### Summary
This PR refactors `RidesTable` to use the new table components in #149 

### Test Plan 
Remove the `date=${today}` query from the fetch endpoint in `ScheduledTable` and `UnscheduledTable` components to see all rides.

image

image

### Notes 
Modified `ScheduledTable` props to support both rider and driver information since `ExportPreview` also uses `ScheduledTable`.

Old props:
```
type ScheduledTableProp = {
  driverId: string;
  driverName: string;
};
```

Generalized props:
```
type ScheduledTableProp = {
  query: string; // either 'rider' or 'driver'
  id: string;
  name: string;
};
```

### Breaking Changes 
Added `width: '100%'` to `TableComponent` to fix the row width from being too small. This does not affect any of the existing tables.

image

### CODE REVIEW

**Review by mg2239 — CHANGES_REQUESTED** [review]
sorry about the poor documentation for the table components, there's a prop called `groupStart` that implements the separated row sections, so you didn't need to add it in yourself. 

i fixed the unscheduled table component, but noticed theres no scheduled table. could you add that in too, with the driver sections? you shouldn't need to do anything special for it, all table components are just divs.

**Review by mg2239 — COMMENTED** [review]
looks good, just waiting to get confirmation from PMs/designers whether the rides should be grouped by rider instead of driver

**Review by mg2239 — CHANGES_REQUESTED** [review]
yep should be organized by driver, so just swap so the headers are drivers and columns are rider

**Comment by pihucode** [comment]
> yep should be organized by driver, so just swap so the headers are drivers and columns are rider

Done!

**Review by mg2239 — APPROVED** [review]

**Pull request merged**
