### PR TITLE
added consistent styling for "Add Location"

### PR DESCRIPTION
**Pull request by SGupta101**
### Summary 

This pull request makes the styling of the "Add Location" feature more consistent. The tag header is now above the drop-down box; the header font-size matches the other headers, and drop-down box matches the height and width of the rest of the input boxes.

Screen Shot 2023-03-25 at 12 02 52 PM

### Notes 

The styling looks a bit different on Safari v. Chrome. On Safari, the height does not match the height of the input boxes.

### CODE REVIEW

**Review by pratyush1712 — COMMENTED** [review]
lgtm. pls run `npm run format:check` in root to check for any formatting issues

**Comment by Atikpui007** [comment]
Checked the styling on different browsers and its pretty consistent throughout. 

For the formatting I had the same issues you can hit 
`Command + Shift + P` on mac or `Ctrl + Shift + P ` to open the command palette and search format document. When you hit Enter you choose configure using prettier and it gets it done.

You can also check out this link to have Format on Save enabled [Prettier](https://www.educative.io/answers/how-to-set-up-prettier-and-automatic-formatting-on-vs-code)

**Comment by RohitValiveti** [comment]
Hi Stuti, the formatting looks good! I checked on both browsers and at different sized windows, and the modal seems to be looking good. As for the formatting errors, you probably need an empty Line at the end of the CSS file. I know it seems pointless, but in my experience GitHub checks the CSS files for and empty line at the end. Then you should be able to merge the PR!

**Review by pratyush1712 — APPROVED** [review]
lgtm! thanks for working on this feature! good work!

**Pull request merged**
