### PR TITLE
Finish ride modal

### PR DESCRIPTION
**Pull request by mg2239**
### Summary 

This pull request adds missing support for:

- Creating a daily, weekly, or custom repeating ride
- Editing a repeating ride (single instance or all repeating rides)

In addition, editing a ride on Rider Web is no longer broken.

### Test Plan 

Run the frontend, and try scheduling a repeating ride. After creation, only the parent repeating ride should be visible in the schedule.

When editing the repeating ride, you can either:

- Edit "this ride only" - the edits made will create a new non-repeating ride on the date specified, and the parent repeating ride start date will move to the next repeat occurrence
- Edit "all repeating rides" - the edits will be made to the parent repeating ride and will affect any future generated repeating rides

image
image
image
image

### Notes 

The `DaySelector` component I used has been created two other times in our codebase, but none of them are reusable without significant code refactoring. This should be fixed as soon as possible!

### Breaking Changes  

<!-- - Database schema change (anything that changes DynamoDB document structure)
<!-- - Other change that could cause problems (Detailed in notes)

### CODE REVIEW

**Comment by mg2239** [comment]
sorry for the big pull request! do your best to understand the code if possible, or just see if you can find any bugs when testing 👍

**Comment by mg2239** [comment]
> I scheduled the following ride to repeat daily, however, it only showed up for the first day as a scheduled ride. The rest of the days until the end date this ride didnt show up. This must be a bug with the repeating rides.
> 
> Screen Shot 2022-02-13 at 2 05 32 PM

this is expected behavior actually, as future repeating rides arent actually created until the day before they occur. on the Rider Web side, we generate fake rides client-side to appear like they're there. Admin Web doesn't currently have code for that

**Comment by tuckerstanley** [comment]
> nice catch! this is expected behavior actually, as future repeating rides arent actually created until the day before they occur. on the Rider Web side, we generate fake rides client-side to appear like they're there. Admin Web doesn't currently have code for that



> > I scheduled the following ride to repeat daily, however, it only showed up for the first day as a scheduled ride. The rest of the days until the end date this ride didnt show up. This must be a bug with the repeating rides.
> > Screen Shot 2022-02-13 at 2 05 32 PM
> 
> nice catch! this is expected behavior actually, as future repeating rides arent actually created until the day before they occur. on the Rider Web side, we generate fake rides client-side to appear like they're there. Admin Web doesn't currently have code for that



> > I scheduled the following ride to repeat daily, however, it only showed up for the first day as a scheduled ride. The rest of the days until the end date this ride didnt show up. This must be a bug with the repeating rides.
> > Screen Shot 2022-02-13 at 2 05 32 PM
> 
> nice catch! this is expected behavior actually, as future repeating rides arent actually created until the day before they occur. on the Rider Web side, we generate fake rides client-side to appear like they're there. Admin Web doesn't currently have code for that

Ok, didn't realize that it only showed up for the next day. That isn't a problem. Another observation that I had was that after editing a ride, the driver becomes unassigned and it goes from a scheduled ride to an unscheduled ride. Just wanted to confirm that this is the intended functionality.

**Comment by mg2239** [comment]
yep thats also intended

**Review by tuckerstanley — APPROVED** [review]
Code looks good, thanks for clarifying my questions. Tested its functionality and it is runnign well.

**Review by tuckerstanley — APPROVED** [review]
Looks good after the merge conflict!

**Pull request merged**
