### PR TITLE
Change px to rem

### PR DESCRIPTION
**Pull request by pihucode**
### Summary 
This PR changed all `px` values to `rem` values. 
The conversion from `px` to `rem` is performed based on a font size of 20px.

### Test Plan
Compare this frontend to the original site to see if there are visual differences.
Alternatively check if the conversions are correct.

### CODE REVIEW

**Review by mg2239 — CHANGES_REQUESTED** [review]
the base font size is 16px, so a lot of the changes unfortunately make things too small

**Comment by pihucode** [comment]
> the base font size is 16px, so a lot of the changes unfortunately make things too small

Whoops, I'll fix that today. For some reason using a base font of 16px makes things small on my screen.

**Comment by mg2239** [comment]
> > the base font size is 16px, so a lot of the changes unfortunately make things too small
> 
> Whoops, I'll fix that today. For some reason using a base font of 16px makes things small on my screen.

is your font size in your browser different from recommended settings?
image

**Comment by pihucode** [comment]
> > > the base font size is 16px, so a lot of the changes unfortunately make things too small
> > 
> > 
> > Whoops, I'll fix that today. For some reason using a base font of 16px makes things small on my screen.
> 
> is your font size in your browser different from recommended settings?
> image

Yes, that is the case. I'll change it to the recommended settings when working on this PR!

**Review by mg2239 — APPROVED** [review]
looks good on my end!

**Pull request merged**
